version: '3.9'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  api:
    container_name: megamouth-api
    build: ./
    tty: true
    volumes:
      - ./:/go/src
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db


  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  dbdata: null